### ISSUE TITLE
今週のやること

### ISSUE THREAD

**Issue by ChasobaAlpacanist** [ChasoProduction/TestWorks#19]

**Comment by ChasobaAlpacanist** [comment]
二週間構成で3章分進めたいと思う。今週はできれば2章分を終わらせたい。

**Comment by nazotti** [comment]
とりあえずどんどん進めて行きます。6章行ければ良いなと思ってます。
ここに書くことではないですが、夏休みの間のアルバイトを、今の時期から出勤を増やすことによって減らしました。お盆などを除いては、本格的に開発を進められると思います。ヤッタァ！！

**Comment by nazotti** [comment]
6章最後まで行けてません
来週には終わらせます。

**Comment by ChasobaAlpacanist** [comment]
一章しか進められなかった。ペースは少し落ちます
