### ISSUE TITLE
進行度の確認

### ISSUE THREAD

**Issue by ChasobaAlpacanist** [ChasoProduction/TestWorks#4]
# 今週のやること(4/6の分)

**Comment by ChasobaAlpacanist** [comment]
Railsもうちょっと進めます。応援して！
具体的にRuby on Rails 5.0の初級4を2章くらい進める。

**Comment by nazotti** [comment]
俺もRailsの勉強を始めます。
https://railstutorial.jp/chapters/rails_flavored_ruby?version=4.2
ここのサイトの1章を終わらせます。
それと聞きたいことが一つ。最終的にはどんなことが出来るようになりたいですか？このサイトに載ってることで大丈夫ですか？

**Comment by ChasobaAlpacanist** [comment]
大丈夫です。まずはRailsとは何か、どんな使い方をすれば良いかを理解し、夏の時点で開発できるようにするのが目的。
最終的には動かし方さえ分かればいい。細かいことはあとでRailsのドキュメントやネットで質問すれば良いだけだから。
**同じもので勉強した方が理解が早いため、私も[そちら](https://railstutorial.jp/chapters/rails_flavored_ruby?version=4.2)で勉強します。**
一週間で1章は進むはず。応援して！Season2

**Comment by ChasobaAlpacanist** [comment]
コマンドでのgitの操作が難しかったら[Sourcetree](https://ja.atlassian.com/software/sourcetree)を使うといい。

**Comment by ChasobaAlpacanist** [comment]
反省：1-4までしか進んでない。

**Comment by nazotti** [comment]
反省：一通り読み進めて、とりあえず動かしたが、とりあえず過ぎてしっかり頭に入っていない
今週は時間が取れてないので、どうにかして平日の通学時間を使って勉強を続けます
